# Generated by Django 3.2 on 2021-05-05 17:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_cliente', models.BooleanField(default=False)),
                ('is_especialista', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
                ('foto', models.ImageField(upload_to='core', verbose_name='Foto')),
                ('idUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ClienteidUsuario', serialize=False, to='core.usuario')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['idUsuario'],
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('dni', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
                ('foto', models.ImageField(upload_to='core', verbose_name='Foto')),
                ('biografia', models.CharField(max_length=255, verbose_name='biografia')),
                ('idUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='EspecialistaidUsuario', serialize=False, to='core.usuario')),
            ],
            options={
                'verbose_name': 'especialista',
                'verbose_name_plural': 'especialistas',
                'ordering': ['idUsuario'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de Mensaje')),
                ('asunto', models.CharField(max_length=50, verbose_name='asunto Mensaje')),
                ('texto', models.TextField(verbose_name='texto Mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='Mensaje leido')),
                ('idEmisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MensajeidEmisor', to=settings.AUTH_USER_MODEL)),
                ('idReceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MensajeidReceptor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAlta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('informe', models.TextField(verbose_name='Cita Texto Informe')),
                ('realizada', models.BooleanField(default=False, verbose_name='Cita realizada')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CitaidCliente', to='core.cliente')),
                ('idEspecialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CitaidEspecialista', to='core.especialista')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['id'],
            },
        ),
    ]
