# Generated by Django 3.2 on 2021-04-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('foto', models.ImageField(upload_to='core/', verbose_name='Foto')),
                ('idUsuario', models.IntegerField(max_length=11, unique=True)),
            ],
        ),
    ]
