# Generated by Django 3.2 on 2021-05-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha'], 'verbose_name': 'cita', 'verbose_name_plural': 'citas'},
        ),
    ]
