# Generated by Django 3.2 on 2021-05-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['fecha'], 'verbose_name': 'mensaje', 'verbose_name_plural': 'mensajes'},
        ),
    ]
