# Generated by Django 3.2 on 2021-04-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210411_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id'], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
