# Generated by Django 3.2 on 2021-04-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='idCLiente'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('idUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='core.cliente')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idMensaje')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de Mensaje')),
                ('asunto', models.CharField(max_length=50, verbose_name='asunto Mensaje')),
                ('texto', models.TextField(verbose_name='texto Mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='Mensaje leido')),
                ('idEmisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mensaje_id_Emisor', to='core.usuario')),
                ('idReceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mensaje_id_Receptor', to='core.usuario')),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idEspecialista')),
                ('dni', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('foto', models.ImageField(upload_to='core', verbose_name='Foto')),
                ('biografia', models.CharField(max_length=255, verbose_name='biografia')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Especialista', to='core.usuario')),
            ],
            options={
                'verbose_name': 'especialista',
                'verbose_name_plural': 'especialistas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idCita')),
                ('fechaAlta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('informe', models.TextField(verbose_name='texto Informe')),
                ('realizada', models.BooleanField(default=False, verbose_name='cita realizada')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cita_idCliente', to='core.cliente')),
                ('idEspecialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cita_idCliente', to='core.especialista')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['id'],
            },
        ),
    ]
