# Generated by Django 3.2 on 2021-05-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(blank=True, default=False, verbose_name='Mensaje leido'),
        ),
    ]
