# Generated by Django 3.2 on 2021-05-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mensaje_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Mensaje leido'),
        ),
    ]
