# Generated by Django 3.2 on 2021-04-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210422_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClienteidUsuario', to='core.usuario'),
        ),
    ]
