# Generated by Django 3.2 on 2021-04-22 16:21

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cliente_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=builtins.id, max_length=20),
            preserve_default=False,
        ),
    ]
