# Generated by Django 3.2 on 2021-04-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuario_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
