# Generated by Django 3.2 on 2021-04-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'verbose_name': 'mensaje', 'verbose_name_plural': 'mensajes'},
        ),
    ]
