# Generated by Django 3.2 on 2021-04-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_mensaje_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'verbose_name': 'cita', 'verbose_name_plural': 'citas'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['id'], 'verbose_name': 'mensaje', 'verbose_name_plural': 'mensajes'},
        ),
    ]
